"""Public Python SDK for Neon3's transport-independent control-plane protocol."""

from .client import NeonClient
from .calculator import CalculatorDomain, CalculatorServer
from .capabilities import CapabilitySet, describe_capabilities, required_capabilities_for_flow, scan_flow, validate_flow_source
from .errors import (
    CapabilityError,
    DropRejectedError,
    DuplicateEventError,
    FlowValidationError,
    InvalidPublicationError,
    NeonError,
    ProtocolError,
    RemoteError,
    StaleRevisionError,
    TransportError,
    UnknownTargetError,
    UnsupportedIntentError,
    normalize_error_code,
)
from .models import (
    AssetRef,
    ClientIdentity,
    DebugSnapshot,
    DropEvent,
    EventEnvelope,
    InputChange,
    InputSlot,
    IntentEvent,
    ProgramInputSnapshot,
    ResolvedInputs,
    ResolvedInputValue,
    RevisionState,
    RpcResponse,
    SemanticInteractionMetadata,
    ServiceDescription,
    ServiceHealth,
    UiFileDropPayload,
    UiProgramRevisionInfo,
    UiSnapshot,
    UiTraceRecord,
)
from .nui import ComponentGallery, GallerySubmission
from .input import InputClient, KeyEvent
from .render import Backend, BackendNegotiation, Camera3D, ColorSpace, ExternalSurface, PointerEvent, RenderClient, SurfaceKind, SurfaceOpen, SurfaceSize, SurfaceTarget, WorldInformation, WorldPlacement
from .routing import DragSource, DropTarget, IntentRouter
from .runtime import RuntimeConfig, RuntimeEndpoints, RuntimeMode, RuntimeSession, default_neon_root, runtime_version
from .session import IntentResult, UiSession
from .store import CollectionStore, ObservableStore, ScalarStore, SelectionStore, typed_value
from .ui import UiClient, UiProgram
from .event import EventClient, EventFilter, EventSubscription
from .wire import CORE_ERROR_CODES, canonical_json, fixture_path, load_fixture

__all__ = [
    "AssetRef",
    "CapabilityError",
    "CapabilitySet",
    "ClientIdentity",
    "CalculatorDomain",
    "CalculatorServer",
    "Camera3D",
    "Backend",
    "BackendNegotiation",
    "CollectionStore",
    "ColorSpace",
    "ComponentGallery",
    "CORE_ERROR_CODES",
    "DebugSnapshot",
    "DragSource",
    "DropEvent",
    "DropRejectedError",
    "DropTarget",
    "DuplicateEventError",
    "FlowValidationError",
    "GallerySubmission",
    "IntentEvent",
    "IntentResult",
    "IntentRouter",
    "ExternalSurface",
    "InputClient",
    "InputSlot",
    "InvalidPublicationError",
    "ProgramInputSnapshot",
    "PointerEvent",
    "KeyEvent",
    "NeonClient",
    "NeonError",
    "ObservableStore",
    "ProtocolError",
    "RemoteError",
    "RenderClient",
    "ResolvedInputs",
    "ResolvedInputValue",
    "RevisionState",
    "RpcResponse",
    "ScalarStore",
    "SemanticInteractionMetadata",
    "SelectionStore",
    "ServiceDescription",
    "ServiceHealth",
    "StaleRevisionError",
    "SurfaceKind",
    "SurfaceOpen",
    "SurfaceSize",
    "SurfaceTarget",
    "TransportError",
    "UnknownTargetError",
    "UnsupportedIntentError",
    "RuntimeConfig",
    "RuntimeEndpoints",
    "RuntimeMode",
    "RuntimeSession",
    "UiClient",
    "UiProgram",
    "UiProgramRevisionInfo",
    "UiSession",
    "UiSnapshot",
    "UiTraceRecord",
    "canonical_json",
    "default_neon_root",
    "describe_capabilities",
    "fixture_path",
    "load_fixture",
    "normalize_error_code",
    "required_capabilities_for_flow",
    "runtime_version",
    "scan_flow",
    "typed_value",
    "validate_flow_source",
    "EventClient",
    "EventFilter",
    "EventSubscription",
    "EventEnvelope",
    "InputChange",
    "UiFileDropPayload",
    "WorldPlacement",
    "WorldInformation",
]
