"""Public Python SDK for Neon3's transport-independent control-plane protocol."""

from .client import NeonClient
from .calculator import CalculatorDomain, CalculatorServer
from .errors import NeonError, ProtocolError, RemoteError, TransportError
from .models import (
    AssetRef,
    ClientIdentity,
    DebugSnapshot,
    EventEnvelope,
    InputChange,
    InputSlot,
    ProgramInputSnapshot,
    ResolvedInputs,
    ResolvedInputValue,
    RevisionState,
    RpcResponse,
    SemanticInteractionMetadata,
    ServiceDescription,
    ServiceHealth,
    UiFileDropPayload,
    UiProgramRevisionInfo,
    UiSnapshot,
    UiTraceRecord,
)
from .nui import ComponentGallery, GallerySubmission
from .input import InputClient, KeyEvent
from .render import Backend, BackendNegotiation, Camera3D, ColorSpace, ExternalSurface, PointerEvent, RenderClient, SurfaceKind, SurfaceOpen, SurfaceSize, SurfaceTarget, WorldInformation, WorldPlacement
from .runtime import RuntimeConfig, RuntimeEndpoints, RuntimeMode, RuntimeSession, default_neon_root, runtime_version
from .ui import UiClient, UiProgram
from .event import EventClient, EventFilter, EventSubscription
from .wire import CORE_ERROR_CODES, canonical_json, fixture_path, load_fixture

__all__ = [
    "AssetRef",
    "ClientIdentity",
    "CalculatorDomain",
    "CalculatorServer",
    "Camera3D",
    "Backend",
    "BackendNegotiation",
    "ColorSpace",
    "ComponentGallery",
    "CORE_ERROR_CODES",
    "DebugSnapshot",
    "GallerySubmission",
    "ExternalSurface",
    "InputClient",
    "InputSlot",
    "ProgramInputSnapshot",
    "PointerEvent",
    "KeyEvent",
    "NeonClient",
    "NeonError",
    "ProtocolError",
    "RemoteError",
    "RenderClient",
    "ResolvedInputs",
    "ResolvedInputValue",
    "RevisionState",
    "RpcResponse",
    "SemanticInteractionMetadata",
    "ServiceDescription",
    "ServiceHealth",
    "SurfaceKind",
    "SurfaceOpen",
    "SurfaceSize",
    "SurfaceTarget",
    "TransportError",
    "RuntimeConfig",
    "RuntimeEndpoints",
    "RuntimeMode",
    "RuntimeSession",
    "UiClient",
    "UiProgram",
    "UiProgramRevisionInfo",
    "UiSnapshot",
    "UiTraceRecord",
    "canonical_json",
    "default_neon_root",
    "fixture_path",
    "load_fixture",
    "runtime_version",
    "EventClient",
    "EventFilter",
    "EventSubscription",
    "EventEnvelope",
    "InputChange",
    "UiFileDropPayload",
    "WorldPlacement",
    "WorldInformation",
]
