"""Public Python SDK for Neon3's transport-independent control-plane protocol."""

from .client import NeonClient
from .android import AndroidConfig, AndroidSession
from .app import NeonApp, InboundOutcome
from .calculator import CalculatorDomain, CalculatorServer
from .constants import AnimationAction, SurfaceKind as ConstSurfaceKind, event_name, method, service
from .facade import FacadeApp, State, mount, on, run, start, state
from .capabilities import CapabilitySet, describe_capabilities, required_capabilities_for_flow, scan_flow, validate_flow_source
from .components import BindingPage, CollectionBinder, CollectionBinding, DragSpec, DropSpec
from .errors import (
    CapabilityError,
    DropRejectedError,
    DuplicateEventError,
    FlowValidationError,
    InvalidPublicationError,
    NeonError,
    ProtocolError,
    RemoteError,
    StaleRevisionError,
    TransportError,
    UnknownTargetError,
    UnsupportedIntentError,
    normalize_error_code,
)
from .models import (
    AssetRef,
    ClientIdentity,
    DebugSnapshot,
    DropEvent,
    EventEnvelope,
    InputChange,
    InputSlot,
    IntentEvent,
    ProgramInputSnapshot,
    ResolvedInputs,
    ResolvedInputValue,
    RevisionState,
    RpcResponse,
    SemanticInteractionMetadata,
    ServiceDescription,
    ServiceHealth,
    UiFileDropPayload,
    UiProgramRevisionInfo,
    UiSnapshot,
    UiTraceRecord,
)
from .nui import ComponentGallery, GallerySubmission
from .input import InputClient, KeyEvent
from .render import Backend, BackendNegotiation, Camera3D, ColorSpace, ExternalSurface, PointerEvent, RenderClient, ShaderPackage, ShaderParameter, SurfaceKind, SurfaceOpen, SurfaceSize, SurfaceTarget, WorldInformation, WorldPlacement, shader_source_digest
from .routing import DragSource, DropTarget, IntentRouter
from .runtime import RuntimeConfig, RuntimeEndpoints, RuntimeMode, RuntimeSession, default_neon_root, runtime_version
from .session import IntentResult, UiSession
from .store import CollectionStore, ObservableStore, ScalarStore, SelectionStore, typed_value
from .ui import UiClient, UiProgram
from .event import EventClient, EventFilter, EventSubscription, ShaderEvent
from .editor import (
    ChangeSet,
    CompletionItem,
    CompletionTriggerKind,
    EDITOR_CHANGE_COMMIT,
    EDITOR_CHANGE_DRAFT,
    EDITOR_LANGUAGE_NUI_FLOW,
    COMPLETION_AUTOMATIC,
    COMPLETION_INVOKED,
    COMPLETION_TRIGGER_CHARACTER,
    MAX_CHANGESET_OPS,
    MAX_INSERT_BYTES,
    EditOp,
    EditorChangeKind,
    EditorClient,
    EditorCompletionResult,
    EditorOpenResult,
    EditorOperationResult,
    EditorPosition,
    EditorSelection,
    EditorSnapshot,
)
from .wire import CORE_ERROR_CODES, canonical_json, fixture_path, load_fixture

__all__ = [
    "AssetRef",
    "AnimationAction",
    "BindingPage",
    "event_name",
    "method",
    "service",
    "CapabilityError",
    "CapabilitySet",
    "ClientIdentity",
    "CalculatorDomain",
    "CalculatorServer",
    "Camera3D",
    "AndroidConfig",
    "AndroidSession",
    "Backend",
    "BackendNegotiation",
    "CollectionBinding",
    "CollectionBinder",
    "CollectionStore",
    "ColorSpace",
    "ComponentGallery",
    "CORE_ERROR_CODES",
    "DebugSnapshot",
    "ChangeSet",
    "CompletionItem",
    "CompletionTriggerKind",
    "DragSource",
    "DragSpec",
    "DropEvent",
    "DropRejectedError",
    "DropSpec",
    "DropTarget",
    "DuplicateEventError",
    "FlowValidationError",
    "GallerySubmission",
    "EditOp",
    "EditorChangeKind",
    "EditorClient",
    "EditorCompletionResult",
    "EditorOpenResult",
    "EditorOperationResult",
    "EditorPosition",
    "EditorSelection",
    "EditorSnapshot",
    "EDITOR_CHANGE_COMMIT",
    "EDITOR_CHANGE_DRAFT",
    "EDITOR_LANGUAGE_NUI_FLOW",
    "COMPLETION_AUTOMATIC",
    "COMPLETION_INVOKED",
    "COMPLETION_TRIGGER_CHARACTER",
    "MAX_CHANGESET_OPS",
    "MAX_INSERT_BYTES",
    "IntentEvent",
    "IntentResult",
    "IntentRouter",
    "ExternalSurface",
    "InputClient",
    "InputSlot",
    "InvalidPublicationError",
    "ProgramInputSnapshot",
    "PointerEvent",
    "KeyEvent",
    "NeonClient",
    "NeonApp",
    "InboundOutcome",
    "NeonError",
    "ObservableStore",
    "ProtocolError",
    "RemoteError",
    "RenderClient",
    "ResolvedInputs",
    "ResolvedInputValue",
    "RevisionState",
    "RpcResponse",
    "ScalarStore",
    "SemanticInteractionMetadata",
    "SelectionStore",
    "ServiceDescription",
    "ServiceHealth",
    "ShaderEvent",
    "ShaderPackage",
    "ShaderParameter",
    "shader_source_digest",
    "StaleRevisionError",
    "SurfaceKind",
    "SurfaceOpen",
    "SurfaceSize",
    "SurfaceTarget",
    "TransportError",
    "UnknownTargetError",
    "UnsupportedIntentError",
    "RuntimeConfig",
    "RuntimeEndpoints",
    "RuntimeMode",
    "RuntimeSession",
    "UiClient",
    "UiProgram",
    "UiProgramRevisionInfo",
    "UiSession",
    "UiSnapshot",
    "UiTraceRecord",
    "canonical_json",
    "default_neon_root",
    "describe_capabilities",
    "fixture_path",
    "load_fixture",
    "normalize_error_code",
    "required_capabilities_for_flow",
    "runtime_version",
    "scan_flow",
    "typed_value",
    "validate_flow_source",
    "EventClient",
    "EventFilter",
    "EventSubscription",
    "EventEnvelope",
    "InputChange",
    "UiFileDropPayload",
    "WorldPlacement",
    "WorldInformation",
]
